# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/XDC.xdc

# Block Designs: bd/UART_RX/UART_RX.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX || ORIG_REF_NAME==UART_RX} -quiet] -quiet

# IP: bd/UART_RX/ip/UART_RX_ila_0_0/UART_RX_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX_ila_0_0 || ORIG_REF_NAME==UART_RX_ila_0_0} -quiet] -quiet

# IP: bd/UART_RX/ip/UART_RX_RX_UART_0_0/UART_RX_RX_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX_RX_UART_0_0 || ORIG_REF_NAME==UART_RX_RX_UART_0_0} -quiet] -quiet

# XDC: d:/Vivado/TTCS2/RX_UART/RX_UART.gen/sources_1/bd/UART_RX/UART_RX_ooc.xdc
