set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN E3 [get_ports sys_clock]
set_property PACKAGE_PIN C2 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports Tx_0]
set_property PACKAGE_PIN D10 [get_ports Tx_0]

set_property IOSTANDARD LVCMOS33 [get_ports {data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_0[0]}]
set_property PACKAGE_PIN D9 [get_ports {data_0[0]}]
set_property PACKAGE_PIN C9 [get_ports {data_0[1]}]
set_property PACKAGE_PIN B9 [get_ports {data_0[2]}]
set_property PACKAGE_PIN B8 [get_ports {data_0[3]}]
set_property PACKAGE_PIN A8 [get_ports {data_0[4]}]
set_property PACKAGE_PIN C11 [get_ports {data_0[5]}]
set_property PACKAGE_PIN C10 [get_ports {data_0[6]}]
set_property PACKAGE_PIN A10 [get_ports {data_0[7]}]
