# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# Block Designs: bd/TTCS_1/TTCS_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TTCS_1 || ORIG_REF_NAME==TTCS_1} -quiet] -quiet

# IP: bd/TTCS_1/ip/TTCS_1_RX_UART_0_0/TTCS_1_RX_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TTCS_1_RX_UART_0_0 || ORIG_REF_NAME==TTCS_1_RX_UART_0_0} -quiet] -quiet

# IP: bd/TTCS_1/ip/TTCS_1_RAM_0_0/TTCS_1_RAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TTCS_1_RAM_0_0 || ORIG_REF_NAME==TTCS_1_RAM_0_0} -quiet] -quiet

# IP: bd/TTCS_1/ip/TTCS_1_Mux8_4_0_0/TTCS_1_Mux8_4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TTCS_1_Mux8_4_0_0 || ORIG_REF_NAME==TTCS_1_Mux8_4_0_0} -quiet] -quiet

# IP: bd/TTCS_1/ip/TTCS_1_Mux8_4_1_0/TTCS_1_Mux8_4_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TTCS_1_Mux8_4_1_0 || ORIG_REF_NAME==TTCS_1_Mux8_4_1_0} -quiet] -quiet

# IP: bd/TTCS_1/ip/TTCS_1_Mach_GM_led7_0_0/TTCS_1_Mach_GM_led7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TTCS_1_Mach_GM_led7_0_0 || ORIG_REF_NAME==TTCS_1_Mach_GM_led7_0_0} -quiet] -quiet

# IP: bd/TTCS_1/ip/TTCS_1_freq_divider_0_0/TTCS_1_freq_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TTCS_1_freq_divider_0_0 || ORIG_REF_NAME==TTCS_1_freq_divider_0_0} -quiet] -quiet

# IP: bd/TTCS_1/ip/TTCS_1_CLOCK_16_0_0/TTCS_1_CLOCK_16_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TTCS_1_CLOCK_16_0_0 || ORIG_REF_NAME==TTCS_1_CLOCK_16_0_0} -quiet] -quiet

# IP: bd/TTCS_1/ip/TTCS_1_ila_0_0/TTCS_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TTCS_1_ila_0_0 || ORIG_REF_NAME==TTCS_1_ila_0_0} -quiet] -quiet

# XDC: d:/Vivado/TTCS2/TTCS2_1/TTCS2_1.gen/sources_1/bd/TTCS_1/TTCS_1_ooc.xdc
