set_property IOSTANDARD LVCMOS33 [get_ports clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports rst_0]
set_property PACKAGE_PIN E3 [get_ports clk_0]
set_property PACKAGE_PIN C2 [get_ports rst_0]
set_property IOSTANDARD LVCMOS33 [get_ports Rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports Tx_0]
set_property PACKAGE_PIN A9 [get_ports Rx_0]
set_property PACKAGE_PIN D10 [get_ports Tx_0]

set_property IOSTANDARD LVCMOS33 [get_ports {ou_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ou_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ou_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ou_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ou_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ou_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ou_0[0]}]
set_property PACKAGE_PIN G13 [get_ports {ou_0[6]}]
set_property PACKAGE_PIN B11 [get_ports {ou_0[5]}]
set_property PACKAGE_PIN A11 [get_ports {ou_0[4]}]
set_property PACKAGE_PIN D12 [get_ports {ou_0[3]}]
set_property PACKAGE_PIN E15 [get_ports {ou_0[2]}]
set_property PACKAGE_PIN E16 [get_ports {ou_0[1]}]
set_property PACKAGE_PIN D15 [get_ports {ou_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk_c_0]
set_property PACKAGE_PIN C15 [get_ports clk_c_0]

set_property IOSTANDARD LVCMOS33 [get_ports clk_0_5s_0]
set_property PACKAGE_PIN G6 [get_ports clk_0_5s_0]
