# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# Block Designs: bd/TX_design/TX_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TX_design || ORIG_REF_NAME==TX_design} -quiet] -quiet

# IP: bd/TX_design/ip/TX_design_vio_0_0/TX_design_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TX_design_vio_0_0 || ORIG_REF_NAME==TX_design_vio_0_0} -quiet] -quiet

# IP: bd/TX_design/ip/TX_design_ila_0_0/TX_design_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TX_design_ila_0_0 || ORIG_REF_NAME==TX_design_ila_0_0} -quiet] -quiet

# IP: bd/TX_design/ip/TX_design_TX_UART_0_0/TX_design_TX_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TX_design_TX_UART_0_0 || ORIG_REF_NAME==TX_design_TX_UART_0_0} -quiet] -quiet

# XDC: d:/Vivado/TTCS2/TX_UART/TX_UART.gen/sources_1/bd/TX_design/TX_design_ooc.xdc
